title: "Mobile Programming 2024"
description: >-
  Material for mobile programming course EASV.
source: "./"
incremental: false

# GitHub pages theme
remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme

# Disable source link in header
github:
  is_project_page: false

collections:
  learning_dart:
    output: true
    permalink: /learning-dart/:name
  working_with_collections:
    output: true
    permalink: /working-with-collections/:name