title: "Mobile Programming 2024"
description: >-
  Material for mobile programming course EASV.
source: "docs"
incremental: false

# GitHub pages theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-cayman

# Disable source link in header
github:
  is_project_page: false